# -- Prod ----------------------------------------------------------------------

prod-accounts-payments-PowerUser            = "prod-accounts-payments-PowerUser"
prod-accounts-payments-ViewCloudtrail       = "prod-accounts-payments-ViewCloudtrail"
prod-accounts-payments-ViewOnly             = "prod-accounts-payments-ViewOnly"
prod-accounts-platform-services-ViewOnly    = "prod-accounts-platform-services-ViewOnly"
prod-network-shared-vpcs-ViewOnly           = "prod-network-shared-vpcs-ViewOnly"
prod-pci-app-payments-DatabaseAccess        = "prod-pci-app-payments-DatabaseAccess"
prod-pci-app-payments-KeyCustodianPayments  = "prod-pci-app-payments-KeyCustodianPayments"
prod-pci-app-payments-PowerUser             = "prod-pci-app-payments-PowerUser"
prod-pci-app-payments-ViewCloudtrail        = "prod-pci-app-payments-ViewCloudtrail"
prod-pci-app-payments-ViewOnly              = "prod-pci-app-payments-ViewOnly"
prod-pci-app-pos-alliance-PowerUser         = "prod-pci-app-pos-alliance-PowerUser"
prod-pci-app-pos-alliance-ViewCloudtrail    = "prod-pci-app-pos-alliance-ViewCloudtrail"
prod-pci-app-pos-alliance-ViewOnly          = "prod-pci-app-pos-alliance-ViewOnly"
prod-pci-network-shared-vpcs-PowerUser      = "prod-pci-network-shared-vpcs-PowerUser"
prod-pci-network-shared-vpcs-ViewCloudtrail = "prod-pci-network-shared-vpcs-ViewCloudtrail"
prod-pci-network-shared-vpcs-ViewOnly       = "prod-pci-network-shared-vpcs-ViewOnly"

# -- Sandbox -------------------------------------------------------------------

sandbox-accounts-payments-DatabaseAccess    = "sandbox-accounts-payments-DatabaseAccess"
sandbox-accounts-payments-PowerUser         = "sandbox-accounts-payments-PowerUser"
sandbox-accounts-payments-ViewCloudtrail    = "sandbox-accounts-payments-ViewCloudtrail"
sandbox-accounts-payments-ViewOnly          = "sandbox-accounts-payments-ViewOnly"
sandbox-accounts-platform-services-ViewOnly = "sandbox-accounts-platform-services-ViewOnly"
sandbox-network-shared-vpcs-ViewOnly        = "sandbox-network-shared-vpcs-ViewOnly"
sandbox-network-transit-PowerUser           = "sandbox-network-transit-PowerUser"
sandbox-network-transit-ViewCloudtrail      = "sandbox-network-transit-ViewCloudtrail"
sandbox-network-transit-ViewOnly            = "sandbox-network-transit-ViewOnly"

# -- Shared Services -----------------------------------------------------------

shared-services-area-payments-PowerUser                = "shared-services-area-payments-PowerUser"
shared-services-area-payments-ViewCloudtrail           = "shared-services-area-payments-ViewCloudtrail"
shared-services-area-payments-ViewOnly                 = "shared-services-area-payments-ViewOnly"
shared-services-area-payments-stage-PowerUser          = "shared-services-area-payments-stage-PowerUser"
shared-services-area-payments-stage-ViewCloudtrail     = "shared-services-area-payments-stage-ViewCloudtrail"
shared-services-area-payments-stage-ViewOnly           = "shared-services-area-payments-stage-ViewOnly"
shared-services-area-pos-PowerUser                     = "shared-services-area-pos-PowerUser"
shared-services-area-pos-ViewCloudtrail                = "shared-services-area-pos-ViewCloudtrail"
shared-services-area-pos-ViewOnly                      = "shared-services-area-pos-ViewOnly"
shared-services-dns-PowerUser                          = "shared-services-dns-PowerUser"
shared-services-dns-ViewCloudtrail                     = "shared-services-dns-ViewCloudtrail"
shared-services-dns-ViewOnly                           = "shared-services-dns-ViewOnly"
shared-services-ecr-PowerUser                          = "shared-services-ecr-PowerUser"
shared-services-ecr-ViewCloudtrail                     = "shared-services-ecr-ViewCloudtrail"
shared-services-ecr-ViewOnly                           = "shared-services-ecr-ViewOnly"
shared-services-network-shared-vpcs-ViewOnly           = "shared-services-network-shared-vpcs-ViewOnly"
shared-services-network-transit-PowerUser              = "shared-services-network-transit-PowerUser"
shared-services-network-transit-ViewCloudtrail         = "shared-services-network-transit-ViewCloudtrail"
shared-services-network-transit-ViewOnly               = "shared-services-network-transit-ViewOnly"
shared-services-observability-prod-ViewOnly            = "shared-services-observability-prod-ViewOnly"
shared-services-observability-sandbox-ViewOnly         = "shared-services-observability-sandbox-ViewOnly"
shared-services-observability-stage-ViewOnly           = "shared-services-observability-stage-ViewOnly"
shared-services-pci-app-atlantis-PowerUser             = "shared-services-pci-app-atlantis-PowerUser"
shared-services-pci-app-atlantis-ViewCloudtrail        = "shared-services-pci-app-atlantis-ViewCloudtrail"
shared-services-pci-app-atlantis-ViewOnly              = "shared-services-pci-app-atlantis-ViewOnly"
shared-services-pci-compliance-PowerUser               = "shared-services-pci-compliance-PowerUser"
shared-services-pci-compliance-ViewCloudtrail          = "shared-services-pci-compliance-ViewCloudtrail"
shared-services-pci-compliance-ViewOnly                = "shared-services-pci-compliance-ViewOnly"
shared-services-pci-network-shared-vpcs-PowerUser      = "shared-services-pci-network-shared-vpcs-PowerUser"
shared-services-pci-network-shared-vpcs-ViewCloudtrail = "shared-services-pci-network-shared-vpcs-ViewCloudtrail"
shared-services-pci-network-shared-vpcs-ViewOnly       = "shared-services-pci-network-shared-vpcs-ViewOnly"

# -- Stage ---------------------------------------------------------------------

stage-accounts-payments-PowerUser                      = "stage-accounts-payments-PowerUser"
stage-accounts-payments-ViewCloudtrail       = "stage-accounts-payments-ViewCloudtrail"
stage-accounts-payments-ViewOnly             = "stage-accounts-payments-ViewOnly"
stage-accounts-platform-services-ViewOnly    = "stage-accounts-platform-services-ViewOnly"
stage-network-shared-vpcs-ViewOnly           = "stage-network-shared-vpcs-ViewOnly"
stage-pci-app-payments-DatabaseAccess        = "stage-pci-app-payments-DatabaseAccess"
stage-pci-app-payments-KeyCustodianPayments  = "stage-pci-app-payments-KeyCustodianPayments"
stage-pci-app-payments-PowerUser             = "stage-pci-app-payments-PowerUser"
stage-pci-app-payments-ViewCloudtrail        = "stage-pci-app-payments-ViewCloudtrail"
stage-pci-app-payments-ViewOnly              = "stage-pci-app-payments-ViewOnly"
stage-pci-app-pos-alliance-PowerUser         = "stage-pci-app-pos-alliance-PowerUser"
stage-pci-app-pos-alliance-ViewCloudtrail    = "stage-pci-app-pos-alliance-ViewCloudtrail"
stage-pci-app-pos-alliance-ViewOnly          = "stage-pci-app-pos-alliance-ViewOnly"
stage-pci-network-shared-vpcs-PowerUser      = "stage-pci-network-shared-vpcs-PowerUser"
stage-pci-network-shared-vpcs-ViewCloudtrail = "stage-pci-network-shared-vpcs-ViewCloudtrail"
stage-pci-network-shared-vpcs-ViewOnly       = "stage-pci-network-shared-vpcs-ViewOnly"

# -- Legacy --------------------------------------------------------------------

Prod-PowerUser      = "Prod-PowerUser"
Prod-ViewCloudtrail = "Prod-ViewCloudtrail"
Prod-ViewOnly       = "Prod-ViewOnly"

izettle-planets = "izettle-planets"
izettle-login   = "izettle-login"
izettle-prod    = "izettle-prod"
izettle-test    = "izettle-test"

izettle-login-ViewOnly         = "izettle-login-ViewOnly"
izettle-planets-PowerUser      = "izettle-planets-PowerUser"
izettle-planets-ViewCloudtrail = "izettle-planets-ViewCloudtrail"
izettle-planets-ViewOnly       = "izettle-planets-ViewOnly"
izettle-test-PowerUser         = "izettle-test-PowerUser"
izettle-test-ViewCloudtrail    = "izettle-test-ViewCloudtrail"
izettle-test-ViewOnly          = "izettle-test-ViewOnly"
